### PR TITLE
WIP Fix #18: Update quote, syn, and darling

### LINKED ISSUE #18: Update `darling`, `syn`, and `quote`
`syn` and `quote` just went through a bit of a refactoring of their public APIs, and `darling` can't be updated to `0.3` until we also update our `syn` and `quote`. They all need to be updated in lock step.

### PR DESCRIPTION
**Pull request by TedDriggs**
Many renames and functional transforms are complete. It doesn't build right now, but that's because I'm not clear on what `collect_idents` is supposed to be doing to lifetimes.

### CODE REVIEW

**Comment by bkchr** [comment]
Ohh nice :+1: I started with this also a will ago, but got stuck really quick :( What you mean with `collect_idents` and lifetimes? We need to collect all the lifetimes and only pass it to the stages where they are actually used, the same way as for type parameters. Does that answers your question?

**Comment by TedDriggs** [comment]
@bkchr I think one of the issues is that this is trying to treat lifetimes as idents, and they're not. I've started implementing a trait in `darling` to do this traversal: See TedDriggs/darling#40 for the progress of that. I may do a similar trait, `UsesLifetimes`, which I think would cover this use case.

**Comment by TedDriggs** [comment]
@bkchr I looked over the code more carefully today, and I'm still lost on why it's doing some of the things it's doing:

1. It's treating lifetimes as idents, but may or may not be conflating them with lifetimes? I think what it's trying to do is extract all generic params from the enum that are needed for the per-state struct, but the way it's doing it is really hard for me to follow.
1. For some reason, it's trying to collect idents from `Expr`; I'm not sure what the goal there is, since I'm not aware of ways for expressions to appear in enum declarations, but as a result there are 20+ variants of that which don't have `CollectIdents` implemented.

If I get done with the PR I linked earlier, I may revisit this, but at the moment I don't have the time to push it to the latest versions of the three packages. Apologies.

**Comment by bkchr** [comment]
I created this `CollectIdents` trait and implemented all that stuff. I never used Darling before, so I may taken the wrong way to solve the problem. In general you are right, we collect all idents from lifetimes and type parameters of the per-state structs.
The linked pull requests sounds like something we could use to find the type parameters. Adding `UsesLifetimes` would be required for searching the lifetimes and then we could drop the stuff on our side.

**Comment by TedDriggs** [comment]
@bkchr as a heads-up, the syn 0.14 changes are probably going to make this even more complicated.

**Comment by bkchr** [comment]
Done by: https://github.com/fitzgen/state_machine_future/pull/26

**Pull request closed without merging**
