### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by hcpl**
I tried to replicate the original behaviour as close as possible to keep things simple. As a result, no tests have been modified at all.

### CODE REVIEW

**Comment by bkchr** [comment]
Could you please replace the collect indent stuff with `UsesTypeParam` and `UsesLiftime` traits from darling?

**Comment by hcpl** [comment]
Sorry for the delay, was experimenting with new approaches to the problem.

While I was at it, I tried to streamline the implementation to make it more readable. Comments were replaced as well and explain details of the new algorithm.

Let me know if what I've done was good enough!

**Comment by bkchr** [comment]
First, huge thanks for doing this! Looks much better now with the upstream stuff :)

One last thing and then I would merge this, could you please add a test for https://github.com/fitzgen/state_machine_future/issues/25?
This should probably now be fixed, by using the darling traits.

**Comment by hcpl** [comment]
Funny that I was updating tests when you posted your comment --- guess you were lucky!

**Comment by hcpl** [comment]
Great! Could you please release a new version?

**Comment by bkchr** [comment]
Yeah, will do that :) Already planed to do that :)

**Comment by hcpl** [comment]
Thanks for the release! :tada:

**Pull request merged**
