### PR TITLE
Remove RentToOwn

### PR DESCRIPTION
**Pull request by baloo**
Hello!

Well, first, thanks for making `state_machine_future`. It's great and I like the design of it a lot!

This Pull request changes the api to remove the renttoown behavior. Why? See https://github.com/fitzgen/state_machine_future/pull/49#issuecomment-510561659

The purpose is to come with an api which I find easier and does not have undefined behavior:
```rust
#[macro_use] extern crate state_machine_future;
extern crate futures;

#[derive(Debug, PartialEq, Eq)]
struct MyItem;
#[derive(Debug, PartialEq, Eq)]
enum MyError {
}

#[derive(StateMachineFuture)]
enum MyStateMachine {
    #[state_machine_future(start, transitions(Counter))]
    Start,

    #[state_machine_future(transitions(Ready))]
    Counter(usize),

    #[state_machine_future(ready)]
    Ready(MyItem),

    #[state_machine_future(error)]
    Error(MyError),
}

impl FutureMyStateMachine for MyStateMachine {
    fn poll_start(_start: Start) -> SMPoll<AfterStart, Start, MyError> {
        transition!(AfterStart::Counter(Counter(3)))
    }
    fn poll_counter(counter: Counter) -> SMPoll<AfterCounter, Counter, MyError> {
        let value = counter.0;

        if value == 0 {
            transition!(AfterCounter::Ready(Ready(MyItem)))
        } else {
            not_ready!(Counter(value - 1))
        }
    }
}

use futures::Async;
use futures::future::Future;

#[test]
fn test_state_machine() {
    let mut sm = MyStateMachine::start();

    assert_eq!(sm.poll(), Ok(Async::NotReady));
    assert_eq!(sm.poll(), Ok(Async::NotReady));
    assert_eq!(sm.poll(), Ok(Async::NotReady));
    assert_eq!(sm.poll(), Ok(Async::Ready(MyItem)));
}
```

I also have another branch with an implementation for streams (not commited here):
``` rust
#[macro_use] extern crate state_machine_future;

#[derive(Debug, PartialEq, Eq)]
struct MyItem;
#[derive(Debug, PartialEq, Eq)]
enum MyError {
}

#[derive(StateMachineStream)]
#[state_machine_stream(item = "MyItem")]
enum MyStateMachine {
    #[state_machine_stream(start, transitions(Connect))]
    Start,

    #[state_machine_stream(transitions(Connect))]
    Retry(usize),

    #[state_machine_stream(transitions(ConsumeBody, Retry))]
    Connect(usize),

    #[state_machine_stream(yields, transitions(Complete, Connect))]
    ConsumeBody(usize),

    #[state_machine_stream(eof)]
    Complete,

    #[state_machine_stream(error)]
    Error(MyError),
}

impl StreamMyStateMachine for MyStateMachine {
    fn poll_start(_start: Start) -> SMFPoll<AfterStart, Start, MyError> {
        transition!(AfterStart::Connect(Connect(16)))
    }

    fn poll_connect(connect: Connect) -> SMFPoll<AfterConnect, Connect, MyError> {
        println!("connect {}", connect.0);
        match connect.0 {
            v if v % 4 == 0 => not_ready!(Connect(v - 1)),
            v if v % 8 == 3 => transition!(AfterConnect::ConsumeBody(ConsumeBody(v - 1))),
            v if v % 8 == 7 => transition!(AfterConnect::Retry(Retry(v - 1))),
            _ => unreachable!("bug?"),
        }
    }

    fn poll_retry(retry: Retry) -> SMFPoll<AfterRetry, Retry, MyError> {
        println!("retry {}", retry.0);
        match retry.0 {
            v if v % 8 == 5 => transition!(AfterRetry::Connect(Connect(v - 1))),
            v if v % 8 == 6 => not_ready!(Retry(v - 1)),
            _ => unreachable!("bug?"),
        }
    }

    // enum AfterConsumeBody {
    //     Connect(MyItem, Connect),
    //     Complete,
    // }

    fn poll_consume_body(consume_body: ConsumeBody) -> SMFPoll<AfterConsumeBody, ConsumeBody, MyError> {
        println!("consume_body {}", consume_body.0);
        match consume_body.0 {
            1 => transition!(AfterConsumeBody::Complete),
            v if v % 8 == 1 => transition!(AfterConsumeBody::Connect(MyItem, Connect(v - 1))),
            v if v % 8 == 2 => not_ready!(ConsumeBody(v - 1)),
            _ => unreachable!("bug?"),
        }
    }

}

use futures::Async;
use futures::stream::Stream;

#[test]
fn test_state_machine() {
    let mut sm = MyStateMachine::start();

    assert_eq!(sm.poll(), Ok(Async::NotReady)); // -> 15
    assert_eq!(sm.poll(), Ok(Async::NotReady)); // -> 13
    assert_eq!(sm.poll(), Ok(Async::NotReady)); // -> 11
    assert_eq!(sm.poll(), Ok(Async::NotReady)); // -> 9
    assert_eq!(sm.poll(), Ok(Async::Ready(Some(MyItem)))); // -> 8

    assert_eq!(sm.poll(), Ok(Async::NotReady)); // -> 7
    assert_eq!(sm.poll(), Ok(Async::NotReady)); // -> 5
    assert_eq!(sm.poll(), Ok(Async::NotReady)); // -> 3
    assert_eq!(sm.poll(), Ok(Async::NotReady)); // -> 1
    assert_eq!(sm.poll(), Ok(Async::Ready(None)));
    assert_eq!(sm.poll(), Ok(Async::Ready(None)));
}
```

The purpose of opening this pull request is to check whether you would be open to a change in the api like this or not :)

Thanks!

### CODE REVIEW

**Comment by bkchr** [comment]
Hey, Ty, but I don't think that you understand the purpose of renttoown. I did not look into your code, but in your example you only use copyable types. How does your solution works without copyable types?

**Comment by bkchr** [comment]
Okay I took a closer look. I'm still not convinced. This breaks all the normal behavior you how you normally work with futures.

**Comment by baloo** [comment]
Hello @bkchr,

Thanks for the replies!
First I should probably explain why I want to remove RentToOwn:
```rust
extern crate futures;
extern crate state_machine_future;

use futures::{Poll, Async, Future};
use state_machine_future::{RentToOwn, StateMachineFuture};

#[derive(StateMachineFuture)]
pub enum Fsm {
    #[state_machine_future(start)]
    #[state_machine_future(transitions(Done))]
    Begin(bool),

    #[state_machine_future(ready)]
    #[state_machine_future(error)]
    Done(()),
}

static mut called: usize = 0;

impl PollFsm for Fsm {
    fn poll_begin<'a>(b: &'a mut RentToOwn<'a, Begin>) -> Poll<AfterBegin, ()> {
        unsafe { called += 1 };
        let b: Begin = b.take();
        drop(b);
        Ok(Async::NotReady)
    }
}

#[test]
fn fsm_ub() {
    let mut fsm = Fsm::start(true);
    unsafe { assert_eq!(called, 0) };
    assert_eq!(fsm.poll(), Ok(Async::NotReady));
    unsafe { assert_eq!(called, 1) };
    assert_eq!(fsm.poll(), Ok(Async::NotReady));
    unsafe { assert_eq!(called, 2) }; // this raises, because the poll did nothing
}
```
This shows a problem with the RentToOwn. As soon as you took ownership, you may **not** return `NotReady`. If you do that, your state machine is stuck. And no compiler can check that behavior may not happen for you. I believe the problem is inherent to the design of the API, and can not be fixed without changing it. I do not believe the API should allow such undefined behavior.

To try to cope with that, I came up with this API, which gives full ownership of the value to the `poll_x_y` methods.
One downside of it, as you noticed, is that the `Future` return should be `Result<Async, Error>` and `Async::NotReady` does not allow to pass in any value. I can not return to `StateMachineFuture` the state I got as parameter.
Therefore, I introduced a change to have a return type like:
```rust
enum SMPoll<R, NR, E> {
   Ready(R),
   NotReady(NR),
   Error(E),
}
``` 

At some point it might be interesting to explore something like:
``` rust
enum SMAsync<R,NR> {
  Ready(R),
  NotReady(NR),
}
type SMPoll<R,NR,E> = Result<SMAsync<R, NR>, E>;
```

see how that can leverage the `try!` / `?` syntaxes, but I'm not sure yet. 

Let me know what you think

**Comment by baloo** [comment]
This last commit changes the signature like:
```rust
enum SMAsync<R,NR> {
  Ready(R),
  NotReady(NR),
}
type SMPoll<R,NR,E> = Result<SMAsync<R, NR>, E>;
```

`poll_x_y` now looks like:
```rust
        fn poll_fail(fail: Fail) -> SMPoll<AfterFail, Fail, MyError> {
            struct SubFut;

            impl Future for SubFut {
                type Item = MyItem;
                type Error = MyError;
                fn poll(&mut self) -> Poll<MyItem, MyError> {
                    Err(MyError)
                }
            }

            let mut subfut = SubFut;
            match subfut.poll()? {
                Async::Ready(item) => transition!(AfterFail::Ready(Ready(item))),
                Async::NotReady => not_ready!(fail),
            }
        }
```
I do not expect this syntax to be unbearable for a consumer of this api.

**Comment by baloo** [comment]
@bkchr any thoughts?

**Comment by fitzgen** [comment]
> This shows a problem with the RentToOwn. As soon as you took ownership, you may **not** return `NotReady`. If you do that, your state machine is stuck. And no compiler can check that behavior may not happen for you. I believe the problem is inherent to the design of the API, and can not be fixed without changing it. I do not believe the API should allow such undefined behavior.

This points to the need for an assertion in the generated code, because yes, you shouldn't do that. You should only `take` the value when you are transitioning states.

**However, this is not [undefined behavior](https://raphlinus.github.io/programming/rust/2018/08/17/undefined-behavior.html).** There is no `unsafe` here nor anything that opens the nasal demon flood gates.

Despite this one bug, `RentToOwn` is serving a purpose here: there is some data that you might be taking ownership of or might not (depending on if you are transitioning states).

The alternative API design (which upon re-reading, you also arrived at) would be to diverge further from the standard future polling method signature by giving unconditional ownership to the `poll` method, and then having returning `NotReady` take ownership back again:

```rust
enum MyAsync<T, AfterT> {
    NotReady(T),
    Ready(AfterT),
}

trait PollMyStateMachine {
    fn poll_foo(foo: Foo) -> MyAsync<Foo, AfterFoo> {
        // Now in here we have unconditional ownership of `foo`, but if we don't
        // transition states, then we have to thread ownership back again by
        // passing `foo` to `MyAsync::NotReady(foo)`.
    }
}
```

I don't have a super clear idea if that is more burdensome than `RentToOwn` or not.

**Pull request closed without merging**
