### PR TITLE
Fix README.md typo

### PR DESCRIPTION
**Pull request by hcpl**

### CODE REVIEW

**Comment by fitzgen** [comment]
Thanks for the pull request, @hcpl! However, we use `cargo readme` to keep the crate level documentation and the readme in sync, which is why the ci is failing. Can you make the change to src/lib.rs and regenerate the readme? If not, then I can do it later. Let me know, thanks again!

**Comment by hcpl** [comment]
Yeah, I'm tackling this right now, though I was distracted by a weird behaviour of `cargo readme` for a moment (this is probably an upstream issue, so this PR will be fixed quickly).

**Comment by hcpl** [comment]
Turns out, the weird behaviour I was wrapping my head around was inability of build script to detect absence of `cargo readme` on my `$PATH`. This resulted in failure not when it was trying to call `cargo readme`, but when comparing `actual` and `expected`.

**Comment by fitzgen** [comment]
> UPD: Found the reason: the test uses the stdout field from std::process::Output without checking for status. Should I fix that in this PR?

Let's make that change as a new PR so we can fix this typo sooner ;)

**Comment by hcpl** [comment]
Okay, then I'll wait for this to get merged first, and then send a PR based on new master :)

**Comment by fitzgen** [comment]
Merged -- thanks!

**Pull request merged**
